# -*- coding: utf-8 -*-
"""Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SiLZaflpm5ZKQEmb4vCuyAKcRHpfJKEk
"""



from langchain_community.document_loaders import PyPDFLoader

file_path = "sdg.pdf"
loader = PyPDFLoader(file_path)

docs = loader.load()

print(docs)

import pprint

pprint.pp(docs[0].metadata)

from langchain_text_splitters import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(chunk_size=1500, chunk_overlap=100)
texts = text_splitter.split_text("docs")

from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_chroma import Chroma

embeddings = HuggingFaceEmbeddings(
    model_name="all-MiniLM-L6-v2"
)

vectorstore = Chroma.from_documents(
    documents=docs,
    embedding=embeddings,
    persist_directory="./chroma_db"
)

retriever = vectorstore.as_retriever()

from langchain_core.prompts import ChatPromptTemplate

prompt = ChatPromptTemplate.from_template("""
You are an assistant for question-answering tasks. Use the following pieces of retrieved context to answer the question. If you don't know the answer, just say that you don't know. Use three sentences maximum and keep the answer concise.
Question: {question}
Context: {context}
Answer:
""")

import os
os.environ["HUGGINGFACEHUB_API_TOKEN"] = "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"

from langchain_huggingface import HuggingFaceEndpoint, ChatHuggingFace

endpoint = HuggingFaceEndpoint(
    repo_id="mistralai/Mistral-7B-Instruct-v0.2",
    task="conversational",
    temperature=0.3,
    max_new_tokens=512
)

llm = ChatHuggingFace(llm=endpoint)

from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser

def format_docs(docs):
  return "\n".join(doc.page_content for doc in docs)

rag_chain = ({"context" : retriever | format_docs, "question" : RunnablePassthrough() }
             | prompt
             | llm
             | StrOutputParser()
             )

rag_chain.invoke("What are the factors influencing the implementation of crop diversification ?")

rag_chain.invoke("What is the summary ?")

from langchain_core.runnables import RunnableLambda

def print_prompt(prompt_text):
  print("Prompt -" , prompt_text)
  return prompt_text

rag_chain_with_print = ({"context" : retriever | format_docs, "question" : RunnablePassthrough() }
             | prompt
             | RunnableLambda(print_prompt)
             | llm
             | StrOutputParser()
             )

rag_chain_with_print.invoke("What contributions can i make ? ")

rag_chain.invoke("What is the conclusion ?")

import streamlit as st
import os

st.set_page_config(page_title="RAG Chatbot")
st.title("🤖 My RAG Chatbot")

if "messages" not in st.session_state:
    st.session_state.messages = []

for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])

if question := st.chat_input("Ask your question"):
    st.session_state.messages.append({"role": "user", "content": question})

    docs = retriever.invoke(question)
    context = "\n\n".join([d.page_content for d in docs])

    chain = prompt | llm
    answer = chain.invoke({
        "context": context,
        "question": question
    })

    st.session_state.messages.append(
        {"role": "assistant", "content": answer}
    )

    with st.chat_message("assistant"):
        st.markdown(answer)
